[package]
name = "gura-rs"
version = "0.1.0"
authors = ["JWare Solutions <jware.organization@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.10.1"
unicode-segmentation = "1.7.1"
regex = "1.5.4"
indexmap = "1.7.0"

[dev-dependencies]
tempfile = "3.2.0"